for i in range(24):
    print("*", end='')
print("\n")
print('{:<30}'.format('*'))
print('{:^30}'.format('NYUGTA'))
print('{:>30}'.format('*'))
for i in range(24):
    print("*", end='')
print("\n")
print('{:<30}'.format('tétel1'))
print('{:>30}'.format('1234.20 Ft'))
print("\n")
print('{:<30}'.format('tétel2'))
print('{:>30}'.format('45.12 Ft'))
print("\n")
print('{:<30}'.format('tétel3'))
print('{:>30}'.format('232.35 Ft'))
for i in range(24):
    print("=", end='')
print("\n")
print('{:<30}'.format('Összesen:'))
print('{:>30}'.format('1511.67 Ft'))
print("\n")
print('{:<30}'.format('Szervízdíj:'))
print('{:>30}'.format('151.17 Ft'))
for i in range(24):
    print("=", end='')
print("\n")
print('{:<30}'.format('Fizetendő:'))
print('{:>30}'.format('1662.84 Ft'))
print('{:<30}'.format('-'))
print('{:<30}'.format('Dátum:'))
print('{:>30}'.format("Név:"))
for i in range(24):
    print("*", end='')
print('{:<30}'.format('*'))
print('{:^30}'.format('CÉG'))
print('{:>30}'.format('*'))
print("\n")
for i in range(24):
    print("*", end='')
